// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceCatalogue.Model;

namespace ServiceCatalogue.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220831090649_ChangedFKs")]
    partial class ChangedFKs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ServiceCatalogue.Model.AppRole", b =>
                {
                    b.Property<int>("AppRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ServerAssetServerId")
                        .HasColumnType("int");

                    b.HasKey("AppRoleId");

                    b.HasIndex("ServerAssetServerId");

                    b.ToTable("AppRole");
                });

            modelBuilder.Entity("ServiceCatalogue.Model.ServerAsset", b =>
                {
                    b.Property<int>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SystemAssetId")
                        .HasColumnType("int");

                    b.HasKey("ServerId");

                    b.HasIndex("SystemAssetId");

                    b.ToTable("ServerAsset");
                });

            modelBuilder.Entity("ServiceCatalogue.Model.SystemAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("LastDeployed")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wiki")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemAsset");
                });

            modelBuilder.Entity("ServiceCatalogue.Model.AppRole", b =>
                {
                    b.HasOne("ServiceCatalogue.Model.ServerAsset", "ServerAsset")
                        .WithMany("Apps")
                        .HasForeignKey("ServerAssetServerId");
                });

            modelBuilder.Entity("ServiceCatalogue.Model.ServerAsset", b =>
                {
                    b.HasOne("ServiceCatalogue.Model.SystemAsset", null)
                        .WithMany("ServerTerms")
                        .HasForeignKey("SystemAssetId");
                });
#pragma warning restore 612, 618
        }
    }
}
